# Generated by Django 3.2.4 on 2021-09-15 21:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=cloudinary.models.CloudinaryField(default='user.png', max_length=255, verbose_name='pic'),
        ),
    ]
