# Generated by Django 3.2.4 on 2021-09-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
