# Generated by Django 5.0.1 on 2024-02-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insta", "0004_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
