# Generated by Django 5.0.1 on 2024-02-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insta", "0005_remove_post_likes_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(max_length=180),
        ),
    ]
