# Generated by Django 5.0.1 on 2024-02-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insta", "0007_story"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="content",
            field=models.FileField(blank=True, null=True, upload_to="stories/"),
        ),
    ]
