# Generated by Django 5.0.1 on 2024-02-15 21:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("insta", "0008_alter_story_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="content",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="stories"
            ),
        ),
    ]
